<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" 
          content="width=device-width, initial-scale=1">
    <title>Learn Online - Retro Tech</title>
    <meta name="description" content="Generated by retro tech">
    <link rel="icon" href="image/logoo.png">
    <link rel="stylesheet" href="./assets/css/index1.css" >
    <link rel="stylesheet" href="./assets/css/index.css">
  
    <script type="text/javascript" src="./assets/js/index.js"></script>

  </head>
